/** Minimal Clerk appearance — AuthShell owns the only card. */
export const clerkAppearance = {
  layout: {
    socialButtonsPlacement: "top",
    socialButtonsVariant: "blockButton",
    logoPlacement: "none" as const,
  },
  variables: {
    colorPrimary: "#55e6ff",
    colorDanger: "#ff6b6b",
    colorSuccess: "#72f1b8",
    colorWarning: "#ffc857",
    colorNeutral: "#8fa3bb",
    colorText: "#f2f8ff",
    colorTextSecondary: "#9db0c7",
    colorTextOnPrimaryBackground: "#07111f",
    colorBackground: "transparent",
    colorInputBackground: "#07111f",
    colorInputText: "#f2f8ff",
    borderRadius: "0.75rem",
    fontFamily: "inherit",
    fontFamilyButtons: "inherit",
    fontSize: "1rem",
    spacingUnit: "0.85rem",
  },
  elements: {
    rootBox: "cl-echobound w-full",
    cardBox: "w-full shadow-none border-0 bg-transparent",
    card: "bg-transparent shadow-none border-0 p-0 gap-4",
    header: "hidden",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    logoBox: "hidden",
    logoImage: "hidden",
    socialButtons: "w-full",
    socialButtonsBlockButton: "w-full",
    formFieldInput: "w-full",
    formButtonPrimary: "mx-auto",
    footer: "bg-transparent mt-3",
    footerAction: "justify-center",
  },
};
